#SPDX-License-Identifier: MIT-0
---
# tasks file for test-role



- name: install nginx
  apt:
    name: nginx
    state: latest

- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes

- name: deploy static webpage
  copy:
    src: files/index.html
    dest: /var/www/html
